/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;

import es.medac.ProyectoInterfaces.Empleado_Recibo;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés
 */
public class InterfazRecibo extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRecibo
     */
    public InterfazRecibo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupInforme = new javax.swing.ButtonGroup();
        jButtonSalirRecibo = new javax.swing.JButton();
        jLabel1TextReciboEmpleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextDni = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jComboBoxEstudios = new javax.swing.JComboBox<>();
        jTextAñoExperiencia = new javax.swing.JTextField();
        jTextHorasTrabajadas = new javax.swing.JTextField();
        jTextPagoPorHora = new javax.swing.JTextField();
        jScrollPanelRecibo = new javax.swing.JScrollPane();
        jTextAreaRecibo = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextRecibo = new javax.swing.JTextField();
        jButtonVolverAlMenu = new javax.swing.JButton();
        jButtonProcesarRecibo = new javax.swing.JButton();
        jButtonDescarga = new javax.swing.JButton();
        jLabelFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalirRecibo.setText("SALIR");
        jButtonSalirRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirReciboActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 100, -1));

        jLabel1TextReciboEmpleado.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1TextReciboEmpleado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1TextReciboEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1TextReciboEmpleado.setText("RECIBO EMPLEADO");
        getContentPane().add(jLabel1TextReciboEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estudios:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Años de Experiencia:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Horas trabajadas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pago por Hora:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, -1));
        getContentPane().add(jTextApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, -1));
        getContentPane().add(jTextDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, -1));
        getContentPane().add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 70, -1));
        getContentPane().add(jTextEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, -1));

        jComboBoxEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Universitario", "Secundaria", "FP" }));
        getContentPane().add(jComboBoxEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));
        getContentPane().add(jTextAñoExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 70, -1));
        getContentPane().add(jTextHorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 70, -1));
        getContentPane().add(jTextPagoPorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 70, -1));

        jTextAreaRecibo.setColumns(20);
        jTextAreaRecibo.setRows(5);
        jScrollPanelRecibo.setViewportView(jTextAreaRecibo);

        getContentPane().add(jScrollPanelRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 460, 240));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Recibo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jTextRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextReciboActionPerformed(evt);
            }
        });
        getContentPane().add(jTextRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 70, -1));

        jButtonVolverAlMenu.setText("VOLVER");
        jButtonVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAlMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 100, -1));

        jButtonProcesarRecibo.setText("PROCESAR");
        jButtonProcesarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarReciboActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProcesarRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 100, -1));

        jButtonDescarga.setText("DESCARGAR");
        jButtonDescarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescargaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDescarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 100, -1));

        jLabelFondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/smooth-soft-and-blurred-liquid-foil-trendy-colorful-green-gradient-modern-cover-template-blur-design-background-for-flyer-social-media-post-screen-mobile-app-wallpaper-free-vector.jpg"))); // NOI18N
        jLabelFondo1.setText("jLabel1");
        getContentPane().add(jLabelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirReciboActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirReciboActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextReciboActionPerformed

    private void jButtonVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAlMenuActionPerformed
        // TODO add your handling code here:
        Interfaz1 interfaz1 = new Interfaz1();
        interfaz1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverAlMenuActionPerformed

    private void jButtonProcesarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarReciboActionPerformed
        String nombre = jTextNombre.getText();
        String apellido = jTextApellidos.getText();
        String dni = jTextDni.getText();
        String direccion = jTextDireccion.getText();
        int edad = Integer.parseInt(jTextEdad.getText());
        String formacionAcademica = (String) jComboBoxEstudios.getSelectedItem();
        int añosExperiencia = Integer.parseInt(jTextAñoExperiencia.getText());
        int horas_trabajadas = Integer.parseInt(jTextHorasTrabajadas.getText());
        int pagoPorHora = Integer.parseInt(jTextPagoPorHora.getText());
        String recibo = jTextRecibo.getText();
        
        
        Empleado_Recibo recibo1 = new Empleado_Recibo(nombre,apellido,dni,
                direccion,edad,formacionAcademica,añosExperiencia,
                horas_trabajadas,pagoPorHora,recibo);
        
        String recibo2 = recibo1.imprimirReciboPago();
        jTextAreaRecibo.setText(recibo2);
    }//GEN-LAST:event_jButtonProcesarReciboActionPerformed

    private void jButtonDescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescargaActionPerformed
        jTextAreaRecibo.requestFocusInWindow();
        String textoRecibo = jTextAreaRecibo.getText();
        
        JFileChooser descargar = new JFileChooser();
        descargar.setDialogTitle("Guarda aquí tu archivo");
        descargar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int seleccion = descargar.showSaveDialog(null);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){
            File carpetaSeleccionada = descargar.getSelectedFile();
            String rutaArchivo = carpetaSeleccionada.getAbsolutePath()+ "/recibo.txt";
            
            try (BufferedWriter leer = new BufferedWriter(new FileWriter(rutaArchivo))){
                
                leer.write(textoRecibo);
                JOptionPane.showMessageDialog(null,"Recibo descargado con éxito", "Descarga Completada",JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,"Error al descargar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonDescargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRecibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInforme;
    private javax.swing.JButton jButtonDescarga;
    private javax.swing.JButton jButtonProcesarRecibo;
    private javax.swing.JButton jButtonSalirRecibo;
    private javax.swing.JButton jButtonVolverAlMenu;
    private javax.swing.JComboBox<String> jComboBoxEstudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1TextReciboEmpleado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo1;
    private javax.swing.JScrollPane jScrollPanelRecibo;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextArea jTextAreaRecibo;
    private javax.swing.JTextField jTextAñoExperiencia;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextHorasTrabajadas;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPagoPorHora;
    private javax.swing.JTextField jTextRecibo;
    // End of variables declaration//GEN-END:variables
}
